package report

import (
	"fmt"
	"io"
	"strings"
)

// WriteMarkdown renders r as report.md: episode header, summary, takeaways,
// quotes with timestamps, topic tags and a fact-check table. Opinion claims
// are left out of the table since there is nothing to check.
func (r *Report) WriteMarkdown(w io.Writer) error {
	var b strings.Builder

	r.writeHeader(&b)
	r.writeSummary(&b)
	r.writeTakeaways(&b)
	r.writeQuotes(&b)
	r.writeTopics(&b)
	r.writeFactCheck(&b)
	r.writeFooter(&b)

	if _, err := io.WriteString(w, b.String()); err != nil {
		return fmt.Errorf("report: write markdown: %w", err)
	}
	return nil
}

func (r *Report) writeHeader(b *strings.Builder) {
	title := r.Episode.Title
	if title == "" {
		title = r.Episode.ID
	}
	fmt.Fprintf(b, "# %s\n\n", oneLine(title))

	var meta []string
	if r.Episode.ID != "" {
		meta = append(meta, fmt.Sprintf("**Episode:** %s", r.Episode.ID))
	}
	if r.Episode.Host != "" {
		meta = append(meta, fmt.Sprintf("**Host:** %s", r.Episode.Host))
	}
	if len(r.Episode.Guests) > 0 {
		meta = append(meta, fmt.Sprintf("**Guests:** %s", strings.Join(r.Episode.Guests, ", ")))
	}
	if r.Episode.Duration != "" {
		meta = append(meta, fmt.Sprintf("**Duration:** %s", r.Episode.Duration))
	}
	if len(meta) > 0 {
		fmt.Fprintf(b, "%s\n\n", strings.Join(meta, " · "))
	}
}

func (r *Report) writeSummary(b *strings.Builder) {
	b.WriteString("## Summary\n\n")
	if s := strings.TrimSpace(r.Summary); s != "" {
		fmt.Fprintf(b, "%s\n\n", s)
	} else {
		b.WriteString("_No summary._\n\n")
	}
}

func (r *Report) writeTakeaways(b *strings.Builder) {
	b.WriteString("## 🔹 Key Takeaways\n\n")
	if len(r.Takeaways) == 0 {
		b.WriteString("_No takeaways._\n\n")
		return
	}
	for _, t := range r.Takeaways {
		fmt.Fprintf(b, "- 🔹 %s\n", oneLine(t))
	}
	b.WriteString("\n")
}

func (r *Report) writeQuotes(b *strings.Builder) {
	b.WriteString("## 💬 Notable Quotes\n\n")
	if len(r.Quotes) == 0 {
		b.WriteString("_No quotes._\n\n")
		return
	}
	for _, q := range r.Quotes {
		fmt.Fprintf(b, "> “%s”\n>\n> — %s\n\n", oneLine(q.Text), attribution(q.Speaker, q.Timestamp))
	}
}

func (r *Report) writeTopics(b *strings.Builder) {
	b.WriteString("## 🧭 Topics\n\n")
	if len(r.Topics) == 0 {
		b.WriteString("_No topics._\n\n")
		return
	}
	tags := make([]string, len(r.Topics))
	for i, t := range r.Topics {
		tags[i] = "`" + strings.ReplaceAll(oneLine(t), "`", "'") + "`"
	}
	fmt.Fprintf(b, "%s\n\n", strings.Join(tags, " "))
}

func (r *Report) writeFactCheck(b *strings.Builder) {
	b.WriteString("## Fact-Check\n\n")
	switch r.FactCheck.Status {
	case StatusPartial:
		b.WriteString("> ⚠ Fact-check did not finish; the claims below are the ones checked before it stopped.\n\n")
	case StatusFailed:
		b.WriteString("> ⚠ Fact-check failed; no claims were checked.\n\n")
	}

	var claims []Claim
	for _, c := range r.FactCheck.Claims {
		if c.Type != ClaimOpinion {
			claims = append(claims, c)
		}
	}
	if len(claims) == 0 {
		if r.FactCheck.Status != StatusFailed {
			b.WriteString("_No checkable claims found._\n\n")
		}
		return
	}

	b.WriteString("| Claim | Verdict | Confidence | Evidence |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, c := range claims {
		claim := cell(c.Claim)
		if a := attribution(c.Speaker, c.Timestamp); a != "" {
			claim += " <br>_— " + cell(a) + "_"
		}
		fmt.Fprintf(b, "| %s | %s | %.2f | %s |\n", claim, verdictLabel(c.Verdict), c.Confidence, evidenceCell(c.Evidence))
	}
	b.WriteString("\n")
}

func (r *Report) writeFooter(b *strings.Builder) {
	if len(r.Run.Warnings) > 0 {
		b.WriteString("## Warnings\n\n")
		for _, w := range r.Run.Warnings {
			fmt.Fprintf(b, "- %s\n", oneLine(w))
		}
		b.WriteString("\n")
	}

	var parts []string
	if r.Run.Provider != "" || r.Run.Model != "" {
		parts = append(parts, strings.Trim(r.Run.Provider+" / "+r.Run.Model, " /"))
	}
	if r.Run.TraceID != "" {
		parts = append(parts, "trace "+r.Run.TraceID)
	}
	if len(parts) > 0 {
		fmt.Fprintf(b, "---\n\n_Generated by %s._\n", strings.Join(parts, " · "))
	}
}

func verdictLabel(v Verdict) string {
	switch v {
	case VerdictVerified:
		return "✅ verified"
	case VerdictOutdatedOrInaccurate:
		return "⚠ outdated or inaccurate"
	case VerdictUnverifiable:
		return "❓ unverifiable"
	default:
		return cell(string(v))
	}
}

func evidenceCell(ev []Evidence) string {
	if len(ev) == 0 {
		return "—"
	}
	items := make([]string, len(ev))
	for i, e := range ev {
		s := cell(e.Source)
		if e.URL != "" {
			s = fmt.Sprintf("[%s](%s)", s, linkTarget(e.URL))
		}
		if e.Date != "" {
			s += " (" + cell(e.Date) + ")"
		}
		items[i] = s
	}
	return strings.Join(items, "<br>")
}

// linkTarget percent-encodes the characters that would end a Markdown link
// target or a table cell early.
var linkTargetEscaper = strings.NewReplacer(" ", "%20", "(", "%28", ")", "%29", "|", "%7C", "<", "%3C", ">", "%3E")

func linkTarget(url string) string {
	return linkTargetEscaper.Replace(strings.TrimSpace(url))
}

// attribution formats "Speaker, 01:20", omitting whichever part is empty.
func attribution(speaker, timestamp string) string {
	parts := make([]string, 0, 2)
	if speaker != "" {
		parts = append(parts, oneLine(speaker))
	}
	if timestamp != "" {
		parts = append(parts, timestamp)
	}
	return strings.Join(parts, ", ")
}

// oneLine collapses whitespace, including newlines, to single spaces so model
// output can't break out of a list item or blockquote.
func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// cell makes s safe inside a Markdown table cell.
func cell(s string) string {
	return strings.ReplaceAll(oneLine(s), "|", `\|`)
}
