// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"context"
	"io"

	"github.com/Rickyxstar/podcast-agent/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockProvider
func (_mock *MockProvider) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockProvider_Expecter) Get(ctx any, key any) *MockProvider_Get_Call {
	return &MockProvider_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockProvider_Get_Call) Run(run func(ctx context.Context, key string)) *MockProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Get_Call) Return(readCloser io.ReadCloser, err error) *MockProvider_Get_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockProvider_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (io.ReadCloser, error)) *MockProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockProvider
func (_mock *MockProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Name() *MockProvider_Name_Call {
	return &MockProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockProvider_Name_Call) Run(run func()) *MockProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Name_Call) Return(s string) *MockProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_Name_Call) RunAndReturn(run func() string) *MockProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockProvider
func (_mock *MockProvider) Put(ctx context.Context, key string, body io.Reader, contentType string) error {
	ret := _mock.Called(ctx, key, body, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) error); ok {
		r0 = returnFunc(ctx, key, body, contentType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockProvider_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - body io.Reader
//   - contentType string
func (_e *MockProvider_Expecter) Put(ctx any, key any, body any, contentType any) *MockProvider_Put_Call {
	return &MockProvider_Put_Call{Call: _e.mock.On("Put", ctx, key, body, contentType)}
}

func (_c *MockProvider_Put_Call) Run(run func(ctx context.Context, key string, body io.Reader, contentType string)) *MockProvider_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProvider_Put_Call) Return(err error) *MockProvider_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_Put_Call) RunAndReturn(run func(ctx context.Context, key string, body io.Reader, contentType string) error) *MockProvider_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockProvider
func (_mock *MockProvider) Stat(ctx context.Context, key string) (*storage.ObjectInfo, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 *storage.ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*storage.ObjectInfo, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *storage.ObjectInfo); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ObjectInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockProvider_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockProvider_Expecter) Stat(ctx any, key any) *MockProvider_Stat_Call {
	return &MockProvider_Stat_Call{Call: _e.mock.On("Stat", ctx, key)}
}

func (_c *MockProvider_Stat_Call) Run(run func(ctx context.Context, key string)) *MockProvider_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Stat_Call) Return(objectInfo *storage.ObjectInfo, err error) *MockProvider_Stat_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockProvider_Stat_Call) RunAndReturn(run func(ctx context.Context, key string) (*storage.ObjectInfo, error)) *MockProvider_Stat_Call {
	_c.Call.Return(run)
	return _c
}
