// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package llm

import (
	"context"

	"github.com/Rickyxstar/podcast-agent/internal/llm"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function for the type MockProvider
func (_mock *MockProvider) Chat(ctx context.Context, req llm.ChatRequest) (*llm.ChatResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *llm.ChatResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, llm.ChatRequest) (*llm.ChatResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, llm.ChatRequest) *llm.ChatResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*llm.ChatResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, llm.ChatRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockProvider_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - req llm.ChatRequest
func (_e *MockProvider_Expecter) Chat(ctx any, req any) *MockProvider_Chat_Call {
	return &MockProvider_Chat_Call{Call: _e.mock.On("Chat", ctx, req)}
}

func (_c *MockProvider_Chat_Call) Run(run func(ctx context.Context, req llm.ChatRequest)) *MockProvider_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 llm.ChatRequest
		if args[1] != nil {
			arg1 = args[1].(llm.ChatRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Chat_Call) Return(chatResponse *llm.ChatResponse, err error) *MockProvider_Chat_Call {
	_c.Call.Return(chatResponse, err)
	return _c
}

func (_c *MockProvider_Chat_Call) RunAndReturn(run func(ctx context.Context, req llm.ChatRequest) (*llm.ChatResponse, error)) *MockProvider_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockProvider
func (_mock *MockProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Name() *MockProvider_Name_Call {
	return &MockProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockProvider_Name_Call) Run(run func()) *MockProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Name_Call) Return(s string) *MockProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_Name_Call) RunAndReturn(run func() string) *MockProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}
